### ISSUE TITLE
Where are the package references checked in?

### ISSUE THREAD

**Issue by NarendraBabuTR** [namitts82/NLPonAZDo#1]
I dont find the package references checked in to repo and this is making the build fail. Please advise.

**Comment by namitts82** [comment]
Which specific package are you looking for?

**Comment by NarendraBabuTR** [comment]
All of below packages @namitts82 

![image](https://github.com/namitts82/NLPonAZDo/assets/89962970/527bc071-770c-4d4a-bb2a-64c0ed31a464)

Since these references arent being able to be downloaded from nuget , the build does not complete successful.

**Comment by NarendraBabuTR** [comment]
Also @namitts82  from where to get the below values?

![image](https://github.com/namitts82/NLPonAZDo/assets/89962970/5425c259-8944-4548-877d-adee92a77836)


and what are these values below in red. Are both ADO pat token?
![image](https://github.com/namitts82/NLPonAZDo/assets/89962970/10ee0ecb-5980-47aa-9e79-63de799d31c8)
